---
title: uBuild Design Blocks
author: Forestry.io
email: support@forestry.io
description: ubuild-jekyll is a Jekyll theme desgined to work with Forestry's Blocks
  feature.  This theme provides a set of page-level components and a pre-configured
  Forestry Blocks UI  that will empower content editors to construct their own webpages.
baseurl: "/"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
markdown: kramdown
gems:
- jekyll-feed
- jekyll-menus
